name = "ClockworkerSMP"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5109c12143324b75a956e4b7714aeebd9657c36bcaa756aaad080ab25fb40c78"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
