name = "ClockworkerSMP"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce98588f7103c81dc0dca8f40bf793b36a8d11738ba0fe441e55cc85f1e1cfd"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
