name = "ClockworkerSMP"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e5b365fb810435e50330405254dca71fbcd12e158fe582a51599330cbe3a5e"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
