name = "ClockworkerSMP"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3722b4f21a9b1c129fc1a8ed423b482b0446e43cb884117290a51ae2ed249264"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
