name = "ClockworkerSMP"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d110c5c7c7eaddeac5f815fc91a928ced055027699de12086ce577571f99ba0d"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
