name = "ClockworkerSMP"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08f036ea92b46520831f8c51322ccde76777b1b32a0204a03c03d9bd7b6cfa5d"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
